export default {
  INIT_CONNECTION: "1",
  JOIN_ROOM: "2",
  EXIT_ROOM: "-2",
  CREATE_ROOM: "5",
  NEXT_SLIDE: "4",
  PREV_SLIDE: "-4",

  SUBMIT_CHOICE: "3",
  RECEIVE_CHOICE: "-3",
  NOT_FOUND_CONTENT: "-5",

  RECEIVE_NEXT_SLIDE_EVENT: "6",
  RECEIVE_PREV_SLIDE_EVENT: "-6",

  SEND_CMT: "7",
  RECEIVE_CMT_EVENT: "-7",
  SEND_QUESTION: "8",
  RECEIVE_QUESTION_EVENT: "-8",

  CLOSE_REASON: "-999",
  REASON_HAS_NEW_CONNECTION: "-998",
  REASON_NOT_FOUND_CONTENT: "-997",
  REASON_NO_PRESENT_PERMISSION: "-996",
  REASON_INVALID_CMD: "-995",
  REASON_WAITING_FOR_HOST: "-994",
  REASON_SLIDE_HAS_NO_ANS: "-993",
  REASON_SELF_HOSTED_PRESENTATION: "-992",
  KICK_CODE: "-100"
};
