export default {
  INIT_CONNECTION: "1",
  JOIN_ROOM: "2",
  EXIT_ROOM: "-2",
  CREATE_ROOM: "5",

  START_MATCH: "4",

  SUBMIT_CHOICE: "3",
  RECEIVE_CHOICE: "-3",
  NOT_FOUND_CONTENT: "-5",
  CLOSE_REASON: "-999",
  REASON_HAS_NEW_CONNECTION: "-998",
  REASON_NOT_FOUND_CONTENT: "-997",
  REASON_NO_PRESENT_PERMISSION: "-996",
  KICK_CODE: "-100"
};
